### ISSUE TITLE
Selecting while search

### ISSUE THREAD

**Issue by hidoon** [SURYAKANTSHARMA/CountryPicker#102]
When search is active, it's needed to tap country twice, i don't know if this is a bug but i think the vc should dismiss when a country is selected.

**Comment by SURYAKANTSHARMA** [comment]
I think we should take it as improvement @ankush-bhatia @Sharkesm want to take it or I will raise PR.

**Comment by SURYAKANTSHARMA** [comment]
@hidoon feel free to raise PR in case.

**Comment by SURYAKANTSHARMA** [comment]
🎉  Congrats

 🚀  SKCountryPicker (2.0.2) successfully published
 📅  April 23rd, 11:53
 🌎  https://cocoapods.org/pods/SKCountryPicker
 👍  Tell your friends!
