### ISSUE TITLE
fatalError in Country.swift

### ISSUE THREAD

**Issue by saeed-rz** [SURYAKANTSHARMA/CountryPicker#103]
**Describe the bug**
I accidentally initiated a Country object with the wrong country code. I think that it might happen in production too because I get the country code from `NBPhoneNumberUtil`.
Is it possible to remove the fatal error and just use the country code as the name in this case?

https://github.com/SURYAKANTSHARMA/CountryPicker/blob/3f3383fd2767ffffb0119b40ed4404fb60100872/CountryPicker/CountryPicker/Country.swift#L79

**Comment by SURYAKANTSHARMA** [comment]
Noted. Can add better check here may be assertFailure what is the expectation in that case it should fail ? 
Can you raise PR @saeed-rz ?

**Comment by SURYAKANTSHARMA** [comment]
🎉  Congrats

 🚀  SKCountryPicker (2.0.2) successfully published
 📅  April 23rd, 11:53
 🌎  https://cocoapods.org/pods/SKCountryPicker
 👍  Tell your friends!
