### ISSUE TITLE
Getting flag from country code

### ISSUE THREAD

**Issue by HarshParekh03** [SURYAKANTSHARMA/CountryPicker#106]
Hello, 
i have used SKcountryPicker in my project in multiple screens such as signUp screen, LoginScreen, EditProfileScreen. So, here the problem is when whenever the country is selected from picker it shows properly after selecting the country in required image and button title. But when i send country code to API and click on submit button of the screen the country code and flag is both set again to default instead of the original selected one

https://user-images.githubusercontent.com/132267828/236448704-651cbcf7-c59e-46ff-b635-ba30d3d4ca28.mp4

**Comment by SURYAKANTSHARMA** [comment]
Can you please share code you are trying ?

version you are using ?

It will be better if you can share sample project with just the issue @HarshParekh03

**Comment by SURYAKANTSHARMA** [comment]
Can you print `CountryManager.shared.lastCountrySelected` it should always give you last country selected back

**Comment by SURYAKANTSHARMA** [comment]
@HarshParekh03  is it resolved did we check.
Please reopen if you still have any issue
