### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by hidoon** [SURYAKANTSHARMA/CountryPicker#108]
When the CountryPickerWithSectionViewController is launched and dismissed, loaded country objects are not released. and if you scroll the whole country from beginning to end, it occupies about 170  MB memory. 
<img width="211" alt="image" src="https://github.com/SURYAKANTSHARMA/CountryPicker/assets/117515125/ba436187-1ed2-45e8-b026-b804af7d7357">

**Comment by SURYAKANTSHARMA** [comment]
Hey we are storing lastSelectedCountry till user kill app
