### ISSUE TITLE
Selected country localisation issue.

### ISSUE THREAD

**Issue by Dev-iOS-Appbirds** [SURYAKANTSHARMA/CountryPicker#117]
**Selected country localisation issue.**

![simulator_screenshot_02FF27C7-0916-4EB5-AD23-F735650D9DBB](https://github.com/SURYAKANTSHARMA/CountryPicker/assets/31612250/dc726626-f5fb-4394-adfe-ab9eb042ef9f)

**Comment by SURYAKANTSHARMA** [comment]
@Dev-iOS-Appbirds please add more detail what version you are facing issue ?
Sample project if u can ?

**Comment by SURYAKANTSHARMA** [comment]
![simulator_screenshot_F2A44ACE-54AB-47E8-91CE-984AE0BE257E](https://github.com/SURYAKANTSHARMA/CountryPicker/assets/6416095/080b8ab4-8de3-4d23-b80b-0309600ddd8f)
@Dev-iOS-Appbirds please check on latest version on example project with swift ui it is working fine.
