### ISSUE TITLE
How to access SwiftUI views using Swift Package Manager?

### ISSUE THREAD

**Issue by jpierceMLD** [SURYAKANTSHARMA/CountryPicker#118]
Using SPM (CountryPicker 3.0.0) I do not see any of the SwiftUI files contained in CountryPicker/CountryPickeriOS15+

**To Reproduce**
Add CountryPicker to Xcode via Swift Package Manager:
![Screenshot 2024-04-16 at 10 37 59](https://github.com/SURYAKANTSHARMA/CountryPicker/assets/25387104/3ce2203b-4e93-4e4a-96f5-0a96d446110c)

The folder CountryPicker/CountryPickeriOS15+/CountryPickerSPM is not present in the dependency and I can't access any of the SwiftUI views that exist in the github project:
![Screenshot 2024-04-16 at 10 38 17](https://github.com/SURYAKANTSHARMA/CountryPicker/assets/25387104/4e5ee0fc-de1d-4679-8374-1d8f16287374)

**Expected behavior**
I should be able to access the SwiftUI files in CountryPicker/CountryPickeriOS15+/CountryPickerSPM for example CountryPickerView

**Comment by SURYAKANTSHARMA** [comment]
Will get back on this

**Comment by SURYAKANTSHARMA** [comment]
@Sharkesm Any idea not sure why it is not fetching

**Comment by SURYAKANTSHARMA** [comment]
@jpierceMLD Feel free to open PR if you can fix ?

**Comment by SURYAKANTSHARMA** [comment]
@jpierceMLD please download SPM from Commit Id c509d3faf6eecca8242850492231a467a9331383
I will publish new version in sometime and let you know. Let me know if still face issue

**Comment by SURYAKANTSHARMA** [comment]
published 4.0.0 you can update to latest
