### ISSUE TITLE
Picker not dismissing

### ISSUE THREAD

**Issue by tobitech** [SURYAKANTSHARMA/CountryPicker#15]
Please the country picker doesn't dismiss when i select a country from a search results

**Comment by SURYAKANTSHARMA** [comment]
@tobitech  Please check why dismiss function won't work may be its your heir achy problem.

**Comment by SURYAKANTSHARMA** [comment]
Or download demo project and then test. Let me know if it don't work.

**Comment by tobitech** [comment]
Oh i just realised one has to click twice to dismiss, but i don't think that should happen. same with demo project as well

**Comment by SURYAKANTSHARMA** [comment]
its intentional. But thanks for suggestion :)

**Comment by mxp7064** [comment]
Hi, this is a great library. Can you please tell me the rationale for making in that way?

**Comment by SURYAKANTSHARMA** [comment]
Thanks @mxp7064  for questioning and kind words.

> Can you please tell me the rationale for making it that way that the user needs to click twice to dismiss?
- There we think that it make more clear for user to tap on country (Tick button appear) . Then user tap for make it selected. If you guys think that it is unclear please reOpen this issue or Make pull request for the same.  Looking forward for your view.

**Comment by SURYAKANTSHARMA** [comment]
@mxp7064 @tobitech  I had update the library with required changes kind check and let me know if don't work for you guys.

**Comment by SURYAKANTSHARMA** [comment]
@mxp7064  yes thanks for remainder had changed but some code start breaking because of conflict so i had reverted the code. Will resolve it shortly Sorry of inconvenience .

**Comment by SURYAKANTSHARMA** [comment]
@mxp7064  Thanks for patience. It's done you can update your pod version 1.2.0. It's done.

**Comment by SURYAKANTSHARMA** [comment]
Welcome @mxp7064, Feel free to give it star if you like it.

**Comment by christianYoopies** [comment]
This issue is still reproduces in case you use search, you have to tap twice to dismiss the control

**Comment by SURYAKANTSHARMA** [comment]
@christianYoopies please attach version you are using ? 
Attach video so that we can rectify better
