### ISSUE TITLE
Image is displayed wrong

### ISSUE THREAD

**Issue by iloo123** [SURYAKANTSHARMA/CountryPicker#16]
Flag Image is stretched is displayed as box. unable give a width to it.

**Comment by SURYAKANTSHARMA** [comment]
@iloo123  could you please explain more ? Screen Shot and code you are trying ..

**Comment by saurabhDuzumaki** [comment]
Hi @SURYAKANTSHARMA I think he meant this.
This issue still persists in version 1.2.0. Please have a look at it. Thanks.
![Simulator Screen Shot - iPhone 7 - 2019-08-02 at 20 47 08](https://user-images.githubusercontent.com/22277943/62380409-c3561100-b566-11e9-8f65-9a4fcc3cefaa.png)

**Comment by SURYAKANTSHARMA** [comment]
ok @saurabhDuzumaki. Thanks for bring.

**Comment by SURYAKANTSHARMA** [comment]
@saurabhDuzumaki Kindly update the latest version 1.2.1 or just pod update. I had resolved and publish the Cocoapod today

**Comment by saurabhDuzumaki** [comment]
I am still using Swift 4.2 (can't update the Xcode because no space in the Mac). When I use 1.2.1, I get the following error at this line `countryImage.image = country.flag` of my project.

2019-08-14 16:11:43.669451+0530 *** NSForwarding: warning: object 0x60000266a8c0 of class 'SKCountryPicker.CountryManager' does not implement methodSignatureForSelector: -- trouble ahead
Unrecognized selector -[SKCountryPicker.CountryManager size]
2019-08-14 16:11:43.669692+0530 Unrecognized selector -[SKCountryPicker.CountryManager size]

**Comment by Sharkesm** [comment]
>@SURYAKANTSHARMA I am still using Swift 4.2 (can't update the Xcode because no space in the Mac). When I use 1.2.1, I get the following error at this line `countryImage.image = country.flag` of my project. There was no such error when I used 1.2.0 ...

@SURYAKANTSHARMA Did this issue occur after merging and testing the last PR? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SURYAKANTSHARMA** [comment]
> @SURYAKANTSHARMA I am still using Swift 4.2 (can't update the Xcode because no space in the Mac). When I use 1.2.1, I get the following error at this line `countryImage.image = country.flag` of my project. There was no such error when I used 1.2.0
> 
> 2019-08-14 16:11:43.669451+0530 *** NSForwarding: warning: object 0x60000266a8c0 of class 'SKCountryPicker.CountryManager' does not implement methodSignatureForSelector: -- trouble ahead
> Unrecognized selector -[SKCountryPicker.CountryManager size]
> 2019-08-14 16:11:43.669692+0530 Unrecognized selector -[SKCountryPicker.CountryManager size]

It's working fine on my end just clone repo and in `Example` folder open the test project and run with version swift 4.2. You should try to clean and try deleting derive data may help.

**Comment by SURYAKANTSHARMA** [comment]
> @SURYAKANTSHARMA Did this issue occur after merging and testing the last PR?

@Sharkesm  Nope. I had tested after merge, run before and after publishing

**Comment by Sharkesm** [comment]
@saurabhDuzumaki Unfortunately I can’t replicate the issue on v1.2.1. Can you share your source code so as we can make a follow and review the problem. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Sharkesm** [comment]
> ...

@SURYAKANTSHARMA Yeap I’m not getting the crush either 😐

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saurabhDuzumaki** [comment]
> You should try to clean and try deleting derive data may help.
This solved the issue for me. There is no crash now. Thanks.
