### ISSUE TITLE
how change the default country  ?  from US to another country ? 

### ISSUE THREAD

**Issue by Ghazzway** [SURYAKANTSHARMA/CountryPicker#18]

**Comment by SURYAKANTSHARMA** [comment]
@Ghazzway  Go to General > Language & Region > Region (Change to other country).
After doing this run application you will see updated country.

**Comment by Ghazzway** [comment]
I'm using your demo project when I go to General I can't find the  Language & Region. Thx pro

**Comment by SURYAKANTSHARMA** [comment]
![Simulator Screen Shot - iPhone XR - 2019-03-19 at 08 09 36](https://user-images.githubusercontent.com/6416095/54576545-a937ee00-4a1e-11e9-96b7-fc5e788c1d2a.png)
Go to Setting Application of Simulator/iphone > General you will find this

**Comment by Ghazzway** [comment]
aha from the device ok thanx that fix my issue. but I wondering if  any way to make the default country by code

**Comment by SURYAKANTSHARMA** [comment]
@Ghazzway  Happy to know you had resolve the issue. 
No right now only default country is selected by default and user can select the custom if wants.
Feel free to star if you find the library useful &Fork the repo to make any changes.
Thanks.

**Comment by Ghazzway** [comment]
**thanx for help**
