### ISSUE TITLE
Unable to find a specification for SKCountryPicker

### ISSUE THREAD

**Issue by tobitech** [SURYAKANTSHARMA/CountryPicker#3]
I tried to install this library with cocoapods and I'm getting this error on the terminal `Unable to find a specification for SKCountryPicker`

**Comment by SURYAKANTSHARMA** [comment]
Hi @tobitech,  Thanks for reporting the issue happy to help. Will reply shorty.

**Comment by tobitech** [comment]
Okay, don't bother I already solved the issue with `pod setup`
