### ISSUE TITLE
Any hacktoberfest enthusiastic can contribute PRs on this repo

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [SURYAKANTSHARMA/CountryPicker#32]
Rules

- Can reduce the launch time of pickerView (Please attach statistics if work)
- Can add voice over accessibility
- Test cases are recommended. 
- Add documentation of public apis by jazz (https://github.com/realm/jazzy)
- Add value to project 
- No Spam

**Comment by megandsouza03** [comment]
Hey Suryakant

What are some of the areas/issues I can work on?

**Comment by SURYAKANTSHARMA** [comment]
Hey Megan, Thanks for interest.
You can work on 
1. add test coverage
2. Add documentation by jazz (https://github.com/realm/jazzy)
3. Any think you see is missing 👍

**Comment by megandsouza03** [comment]
Perfect, I'll add some tests soon! 

Is there any feature enhancement you would like me to work on?

**Comment by SURYAKANTSHARMA** [comment]
- Can reduce the launch time of pickerView (Please attach statistics if work)
- Can add voice over accessibility

**Comment by thisIsTheFoxe** [comment]
Hey, just to let you know: I’m currently working on Accessibility support and will PR probably some time tmr (in ~12-16h)

Like the project and that you think about stuff like Accessibility! ^^

**Comment by SURYAKANTSHARMA** [comment]
Yes please @thisIsTheFoxe  Add and generate PR. 💯

**Comment by megandsouza03** [comment]
Hey Suryakant

I'll be writing UITests for the repo, would that be fine? 
Or you have something else in mind?

**Comment by SURYAKANTSHARMA** [comment]
Yes, sure go for it.
