### ISSUE TITLE
Add Swift Package Manager Support for Library

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [SURYAKANTSHARMA/CountryPicker#35]
Anybody interested in Add `Swift Package Manager` support for Library can be take this for PR. Thanks in advance.

**Comment by theaudience** [comment]
I had a look into this. Currently resources are not supported with Swift Package Manager. If anyone knows a suitable workaround I would be happy to take up this issue.

**Comment by SURYAKANTSHARMA** [comment]
@theaudience  Thanks for interest. 💯  I think its the bug  [here](https://bugs.swift.org/browse/SR-2866), and still discussion is going on [forum](https://forums.swift.org/t/swift-pm-bundles-and-resources/13981/44). Let wait for solution by the swift team 👍 . As this [stackoverflow](https://stackoverflow.com/q/39815054/3331528) question still shows no solution of doing the same.

**Comment by theaudience** [comment]
I think one possibility would be to use the iOS country flag icons instead of the images in the library. This would remove the dependency. What do you think @SURYAKANTSHARMA?

**Comment by SURYAKANTSHARMA** [comment]
Yes Please 💯 . Thanks in advance :)
