### ISSUE TITLE
No data when countries in Arabic language

### ISSUE THREAD

**Issue by Dev-Khaled** [SURYAKANTSHARMA/CountryPicker#4]
No data when countries in Arabic language

```
// This code is wrong
    func fetchSectionCountries() {
        for section in sections {
            let sectionCountries = countries.filter({ (country) -> Bool in
                return country.countryName.first! == section
            })
            sectionCoutries[section] = sectionCountries
        }
    }

```

**Comment by SURYAKANTSHARMA** [comment]
Hi @dev thanks for reporting the issue, I think this issue is not in my knowledge I had tested the code and many applications used it, although I couldn't help today but surely look into this Asap. Please share the details so that I can help you smoothly.

**Comment by SURYAKANTSHARMA** [comment]
Nice to know you had solve the problem :1st_place_medal:   could you please explain a bit how it solve the problem?  So that i update my repo accordingly. it is seems like is Duplicacy is the problem (Not clear for me how) ? is it please let me know.

**Comment by Dev-Khaled** [comment]
You get country names from the system, and it depends on device language.

for non English languages, constant "sections" with English letters will be wrong, so I just initiated sections with first letter from each language name, 

`countries.map({ String($0.countryName.prefix(1)).first! })
`
then filtered the duplicates.

`.unique
`
Best

**Comment by SURYAKANTSHARMA** [comment]
ok @Dev-Khaled  thanks for clearification.

**Comment by SURYAKANTSHARMA** [comment]
@Dev-Khaled  Awesome bro 👍 Good Catch 💯 .  #4  Done in version 1.1.6.

**Comment by VRWayVl** [comment]
the same issue with russian language
