### ISSUE TITLE
White search bar in dark mode

### ISSUE THREAD

**Issue by SerggioC** [SURYAKANTSHARMA/CountryPicker#44]
When the search field for the country list is visible the top bar background becomes white.
Isn't it supposed to be black? 
How do we change it to black in dark mode?

edit: when the table view controller is opening the top bar background is black, then when it finishes openning it becomes white...

**Comment by SURYAKANTSHARMA** [comment]
@SerggioC  please upload video or screenshot. It's easy to understand and resolve.

**Comment by SerggioC** [comment]
@SURYAKANTSHARMA 
As you see the table header for the search bar is white in dark mode. It would look better in a darker colour. How do we change that?
![Screenshot 2019-12-19 at 23 00 16](https://user-images.githubusercontent.com/21109275/71216782-6b207100-22b3-11ea-817f-fdf8dc6b4fae.png)

**Comment by SerggioC** [comment]
Using the following code:

            let countryController = CountryPickerWithSectionViewController.presentController(on: self) { [weak self] (country: Country) in
                 // ...
            }
            
            countryController.detailColor = UIColor.red
            countryController.flagStyle = .corner
            countryController.isCountryDialHidden = true
            if #available(iOS 13.0, *) {
                countryController.isModalInPresentation = true
                if self.traitCollection.userInterfaceStyle == .dark {
                    countryController.statusBarStyle = .darkContent
                } else {
                    countryController.statusBarStyle = .lightContent
                }
            }

**Comment by SURYAKANTSHARMA** [comment]
Got It. Will fix ASAP. Thanks @SerggioC

**Comment by SURYAKANTSHARMA** [comment]
Done @SerggioC . Please pod update to latest version   
🎉  Congrats

 🚀  SKCountryPicker (1.2.7) successfully published
 📅  December 21st, 10:50
 🌎  https://cocoapods.org/pods/SKCountryPicker
 👍  Tell your friends!

**Comment by SerggioC** [comment]
@SURYAKANTSHARMA thanks for fixing. Will update today. 
And thanks for the library, it's easy to use and very helpful.

**Comment by SURYAKANTSHARMA** [comment]
welcome @SerggioC . Feel free ⭐ repo. And spread to community so other can find it easily. Feel free to report any other bug/suggestion. Thanks 🙏🏻

**Comment by NikhilDikshit** [comment]
Hey, it says [!] Unable to find a specification for `SKCountryPicker~> 1.2.7`

**Comment by SURYAKANTSHARMA** [comment]
@NikhilDikshit  Please share podfile or pod update without specify the version `SKCountryPicker`
