### ISSUE TITLE
[!] Unable to find a specification for `SKCountryPicker (~> 1.1)`

### ISSUE THREAD

**Issue by anshumanburman** [SURYAKANTSHARMA/CountryPicker#5]
i am  unable to install.
pod version : 1.5.2

**Comment by SURYAKANTSHARMA** [comment]
Hi @anshumanburman , Could you please install this ? 
 pod 'SKCountryPicker'

**Comment by SURYAKANTSHARMA** [comment]
@anshumanburman  are u done with it ?

**Comment by SURYAKANTSHARMA** [comment]
Issue not found. Closed.
