### ISSUE TITLE
4 digits country codes are missing 

### ISSUE THREAD

**Issue by akgrt** [SURYAKANTSHARMA/CountryPicker#51]
Kindly update the countries list, I guess some codes are updated or missing. For eg: +1345, +1268
Thanks.

**Comment by SURYAKANTSHARMA** [comment]
@akgrt will check and update you

**Comment by SURYAKANTSHARMA** [comment]
@akgrt  Thanks for bringing this up 💯 . It's my bad, I had so fix this here. Let me know if you having more improvements or suggestions. 
 🎉  Congrats

 🚀  SKCountryPicker (1.2.8) successfully published
 📅  March 28th, 16:03
 🌎  https://cocoapods.org/pods/SKCountryPicker
 👍  Tell your friends!
