### ISSUE TITLE
CountryManager is not loading countries correctly

### ISSUE THREAD

**Issue by canedo2** [SURYAKANTSHARMA/CountryPicker#52]
Hello! 

I'm having a problem, it seems like CountryManager is not loading countries correctly in my project. I tried to install by using CocoaPods and SPM and it remains the same. I guess it is a configuration problem. 

Console logs: 
### " Could not load the "US.png" image referenced from a nib in the bundle with identifier "com.myproject.debug" " 

As I've tried, actually CountryManager.countries remain empty, so this is not only an image problem.

If there's something I'm missing please, let me know.

**Comment by Sharkesm** [comment]
@canedo2 Thanks for raising this out, reviewing the code base now

**Comment by Sharkesm** [comment]
@canedo2 On what version are you on?

**Comment by SURYAKANTSHARMA** [comment]
@canedo2 could you please check [example](https://github.com/SURYAKANTSHARMA/CountryPicker/tree/master/Example) project in repo and update to latest version.

**Comment by Sharkesm** [comment]
@canedo2 Here's the latest version `1.2.8` for the pod

**Comment by canedo2** [comment]
@Sharkesm Hey! I'm with XCode 11.3.1 using the latest version of the pod. I'll try to compile the example project in order to see if I also have a problem with that.

**Comment by canedo2** [comment]
`error: Build input file cannot be found: '/Users/diegomanuelmolinacanedo/Downloads/CountryPicker-master/Example/Pods/SKCountryPicker/CountryPicker/CountryPicker/CountryPickerController.bundle/XK@2.png' (in target 'SKCountryPicker-CountryPickerController' from project 'Pods')`

That's what I get when I try to compile the example project. 

![Captura de pantalla 2020-04-07 a las 10 52 26](https://user-images.githubusercontent.com/23417387/78649630-fe5ed000-78bd-11ea-9148-f44d7cf0eb53.png)

Another question is, as u can see in the pic, why does it have 2 AppDelegate files?
I'm not into creating frameworks for iOS so I don't actually know if that's normal. 

Thanks for replaying.

**Comment by Sharkesm** [comment]
@canedo2 I think there was a mistake adding the country images as some of them are missing specifically for `Kosovo` (or you may try to clear your Derived Data). 

And, for the duplication of `AppDelegate` proceeding to fix that 😄

**Comment by SURYAKANTSHARMA** [comment]
Thanks, @Sharkesm for taking this up.
@canedo2  Please Check now I had committed the latest code in example project. Don't forget to clean the build folder and delete the drive data. 
P.S Two app delegate should not be the issue I had delete wrong reference anyway.

**Comment by SURYAKANTSHARMA** [comment]
@canado any update ? Issue get resolved ?

**Comment by canado** [comment]
Wrong user, you need to ask again to @canedo2

**Comment by canedo2** [comment]
Hey, sorry, having a hard day, I'll try it asap. Just to clarify, I tried removing derived data and cleaning build folder a few times when i passed from SPM to CocoaPods.

**Comment by SURYAKANTSHARMA** [comment]
@canedo2  Had you tried ?

**Comment by canedo2** [comment]
Hey, sorry, spanish holy week.

<img width="1280" alt="Captura de pantalla 2020-04-13 a las 9 48 57" src="https://user-images.githubusercontent.com/23417387/79102976-14f8a180-7d6c-11ea-8c45-a6639b326db2.png">

It seems like the same problem is showing up. Trying to fix it, I "pod install" in the /Example folder but get a problem with finding de SKCountryPicker module when compiling:

`Use of undeclared type 'CountryPickerView'` (line 31 of PickerViewController) even when SKCountryPicker is imported. Just a comment, in that line the  "let" constant is called picketView if you wanna fix the typo.

**Comment by SURYAKANTSHARMA** [comment]
Deleting drive data might help here.
If not compress and zip it and send it here or email me at Suryakantsharma84@gmail.com. I will revert ASAP.

**Comment by canedo2** [comment]
I just downloaded it from clone or download button.

[CountryPicker-master.zip](https://github.com/SURYAKANTSHARMA/CountryPicker/files/4470219/CountryPicker-master.zip)

**Comment by SURYAKANTSHARMA** [comment]
Thanks @canedo2  I got your issue. It's weird but run following commands 
1. `pod deintegrate`
2. `pod install`
This is due to some cocoa pods reference issues. Let me know if you still face issue after doing this. It works fine for me after that.

**Comment by Sharkesm** [comment]
@SURYAKANTSHARMA Yeah, noticed the same issue with me though it worked after reinstalling the newer version.

**Comment by SURYAKANTSHARMA** [comment]
Closing this issue
