### ISSUE TITLE
Favourite group in country code list

### ISSUE THREAD

**Issue by phillipjacobs** [SURYAKANTSHARMA/CountryPicker#53]
**Please consider adding a "favorite" section.**
where we could set the favorites and it would display in the CountryPickerWithSectionViewController on the top.

Great job on this project!!

**Comment by SURYAKANTSHARMA** [comment]
@phillipjacobs  Good Idea.
 How will we adding countries to favourite ? Could you suggest any strategy.

**Comment by phillipjacobs** [comment]
Hi,

I don't know exactly how you setup your code structure but if possible:

- Have a property we can set: "showFavorites"
- Then have three functions similar to your add, remove, removeAll filter
functions:

• addFavorite(withCode: "TZ")

• removeFavorite(withCode: "TZ")

• removeAllFavorites()


- Add another section "Favorites" (only if "showFavorites" was set to true)
- This section will pull its data from the same list that the search-filter
is pulling from.
- The section will then filter through the list for country codes that
match the ones in the (private) favorite list.

Will that be something that's possible on your side ?

**Comment by SURYAKANTSHARMA** [comment]
@phillipjacobs  yes we can do this at code end but how end user add favourite ? e.g new screen or  some extra button should be there. Have you seen anything related to this which might help me to understand the design

**Comment by phillipjacobs** [comment]
Hi,

I misunderstood your previous email. Apologies.

Yes, I saw it from another library.
Both of these libraries have the feature:
• NKVPhonePicker <https://github.com/NikKovIos/NKVPhonePicker>
• CountryPickerView <https://github.com/kizitonwose/CountryPickerView>

All the best,
Phillip

**Comment by SURYAKANTSHARMA** [comment]
ok Thanks @phillipjacobs  Will check

**Comment by SURYAKANTSHARMA** [comment]
I am done with this feature here Add favourite #63 please review @phillipjacobs
