### ISSUE TITLE
NSRangeException - out-of-bounds 

### ISSUE THREAD

**Issue by phillipjacobs** [SURYAKANTSHARMA/CountryPicker#54]
**Error**
Terminating app due to uncaught exception 'NSRangeException', reason: 'Attempted to scroll the table view to an out-of-bounds section (18) when there are only 1 sections..

**When does it happen ?**
It happens when I search "ZA" and there is only one section. When I scroll it breaks. This happens randomly and is not a constant error.

I filter by all three types.

**Comment by SURYAKANTSHARMA** [comment]
cc @hardeep-singh  @Sharkesm

**Comment by Sharkesm** [comment]
@SURYAKANTSHARMA I can't replicate this issue on my side.

**Comment by Sharkesm** [comment]
@phillipjacobs Fix on review mate :)

**Comment by SURYAKANTSHARMA** [comment]
Reviewing Thanks @Sharkesm

**Comment by SURYAKANTSHARMA** [comment]
🎉  Congrats
🚀  SKCountryPicker (1.2.9) successfully published
Please update your pod @phillipjacobs
