### ISSUE TITLE
Country list not loaded when using SPM

### ISSUE THREAD

**Issue by kapadiamoheet** [SURYAKANTSHARMA/CountryPicker#56]
**I am using XCODE 11 'Add Swift Package' feature**

Country list is not loaded. I debugged and found that country.plist is not loaded. Getting log as "Missing contries file path"

**To Reproduce**
1. Go to 'Xcode 11->File->Add Swift Package'
2. Following integration steps to create country button and present country list
3. Country list is not loaded

**Expected behavior**
Country list should be loaded

**Screenshots**
![Screenshot 2020-04-28 at 3 45 51 AM](https://user-images.githubusercontent.com/16037108/80426788-0e3d6300-8904-11ea-8248-f4e2354db104.png)

**Smartphone (please complete the following information):**
 - Device:  iPhone11
 - OS: 13.2.2

**Comment by SURYAKANTSHARMA** [comment]
@mike011  could you please check its also not working for me as well.

**Comment by SURYAKANTSHARMA** [comment]
@mike011  are you looking ?

**Comment by SergLam** [comment]
Faced with the same problem, looks like we need to wait until resources support for SPM feature:

https://stackoverflow.com/questions/39815054/how-to-include-assets-resources-in-a-swift-package-manager-library

https://forums.swift.org/t/se-0271-package-manager-resources/30730/78

**Comment by SURYAKANTSHARMA** [comment]
Any work around for now

**Comment by SergLam** [comment]
@SURYAKANTSHARMA Swift 5.3 introduces resources support for SPM, looks like it possible now:
https://medium.com/swlh/whats-new-in-swift-5-3-ae135c9c259f

**Comment by SURYAKANTSHARMA** [comment]
Thanks, Could you want to give it try ?

**Comment by liambolling** [comment]
Any change to this?

**Comment by SURYAKANTSHARMA** [comment]
@liambolling it still need help

**Comment by Den-creator** [comment]
this issue is still exists

**Comment by SURYAKANTSHARMA** [comment]
@Den-creator could you help to resolve? I am not good with SPM packages creation

**Comment by Den-creator** [comment]
> @Den-creator could you help to resolve? I am not good with SPM packages creation

I will try something when I will have free time
