### ISSUE TITLE
How to use CountryPicker from Objective C project?

### ISSUE THREAD

**Issue by SerggioC** [SURYAKANTSHARMA/CountryPicker#57]
I tried to import the pod with CountryPicker into an Objective-C project but I get a bunch of errors.
used @import SKCountryPicker; where I need to use it but then can't access CountryManager shared etc.
How can this be solved?

Thanks.

**Comment by SURYAKANTSHARMA** [comment]
Hi @SerggioC. Actually we are not supporting this project with objective c for various reasons may be you can use https://github.com/emcrisostomo/EMCCountryPickerController for your project

**Comment by SerggioC** [comment]
Thanks I'll try that.
