### ISSUE TITLE
About localization-related

### ISSUE THREAD

**Issue by trusbe** [SURYAKANTSHARMA/CountryPicker#60]
Hi, good project, can the following functions be added:

1、Manually switch localization?
2、Manually modify the names of some disputed regions?

**Comment by SURYAKANTSHARMA** [comment]
thanks @trusbe  could you elaborate a bit. 

> 1、Manually switch localization?

I think we can but make sure if user default view is current one

**Comment by trusbe** [comment]
@SURYAKANTSHARMA   

Thanks for the reply.

"Manually switch localization?"
It is the localization file, which can be automatically switched without following the language of the system, and the localization file in the application can be changed through the localization switch in the application.

The user will follow the system to display localized files by default;

**Comment by SURYAKANTSHARMA** [comment]
> @SURYAKANTSHARMA   
> 
> Thanks for the reply.
> 
> "Manually switch localization?"
> It is the localization file, which can be automatically switched without following the language of the system, and the localization file in the application can be changed through the localization switch in the application.
> 
> The user will follow the system to display localized files by default;
> 

Sure can do what about 2 point ?

**Comment by trusbe** [comment]
Manually modify the names of some disputed regions?
Regarding the second point, it is mainly for some disputed regions, such as Taiwan (Taiwan, China) and China (China-Taiwan, China), each of which has different names for each other. In order to be able to conform to the local name, it needs to operate locally. In the localization file, it is modified to the local compliant name.

**Comment by SURYAKANTSHARMA** [comment]
Sure. I think we are good to go. Approved.

**Comment by SURYAKANTSHARMA** [comment]
Any update @trusbe ?

**Comment by ablyAnkurPanwar** [comment]
Any updates on 1st point i.e, Manually switch localization ?

**Comment by bhargavthakkar2912** [comment]
Any update on manually changing localization?

**Comment by Sharkesm** [comment]
Looks like @trusbe went MIA, should we proceed to close this issue since there are no more updates?

**Comment by SURYAKANTSHARMA** [comment]
Sure @Sharkesm  💯

**Comment by bhargavthakkar2912** [comment]
How can I localise the country name to Arabic without changing the device language?

**Comment by SURYAKANTSHARMA** [comment]
1 way around is store locally and force rightToLeft rendering on UIKit.

**Comment by bhargavthakkar2912** [comment]
ya it is showing English name in Arabic localisation in RTL
