### ISSUE TITLE
SPM "Missing contries file path" error.

### ISSUE THREAD

**Issue by onurtuna** [SURYAKANTSHARMA/CountryPicker#70]
While using the library with SPM, the error is thrown. The file can not be found under CountryPickerController.bundle. The issue should be related to SPM installation.

After debugging, I see that the file seems to be missing. I will open a PR which should solve the problem.

**Comment by SURYAKANTSHARMA** [comment]
Sure thanks @onurtuna

**Comment by SURYAKANTSHARMA** [comment]
cc @adrum please help verify this issue as it was integrated by #67

**Comment by onurtuna** [comment]
countries.plist is missing for SPM. The images are inside the bundle. Let me open a PR for it. @adrum @SURYAKANTSHARMA

**Comment by SURYAKANTSHARMA** [comment]
@onurtuna  is it fixed ? PR ?

**Comment by SURYAKANTSHARMA** [comment]
it is working for with SPM 💯 Please reopen it if needed
