### ISSUE TITLE
removing last selected country is not working

### ISSUE THREAD

**Issue by bhargavthakkar2912** [SURYAKANTSHARMA/CountryPicker#73]
When I use this controller in two different places I want to remove the last selected country but cannot remove it. Can you please provide me with a way to do it. 

Thanking you in advance

**Comment by SURYAKANTSHARMA** [comment]
@bhargavthakkar2912  Can you please upload video screen shot because its hard to understand otherwise

**Comment by Sharkesm** [comment]
@SURYAKANTSHARMA I got it, there's no method exposed to reset the last selected country.

**Comment by Sharkesm** [comment]
@bhargavthakkar2912 Follow up PR for this request ~ https://github.com/SURYAKANTSHARMA/CountryPicker/pull/78

**Comment by bhargavthakkar2912** [comment]
Great when can we get this change on cocoa pods?

**Comment by Sharkesm** [comment]
cc/ @SURYAKANTSHARMA ☝🏾

**Comment by SURYAKANTSHARMA** [comment]
Will publish in sometime. Today or tomorrow.

**Comment by SURYAKANTSHARMA** [comment]
Done @bhargavthakkar2912 
 🎉  Congrats
 🚀  SKCountryPicker (1.3.2) successfully published
 📅  May 17th, 12:56
 🌎  https://cocoapods.org/pods/SKCountryPicker
 👍  Tell your friends!

**Comment by bhargavthakkar2912** [comment]
Thanks @SURYAKANTSHARMA
