### ISSUE TITLE
Wrong Kazakhstan phone code (have to be +7). Wrong Guyana phone code (have to be +595). 

### ISSUE THREAD

**Issue by freakdragon** [SURYAKANTSHARMA/CountryPicker#74]
**Describe the bug**
Phone code of Kazakhstan is +7 and not +77

You can check it [here](https://countrycode.org/kazakhstan). There are codes of some cities of this country.

**Comment by freakdragon** [comment]
Wikipedia also says Guyana phone code is 592 and not 595

**Comment by SURYAKANTSHARMA** [comment]
For guyana +592 Correct will do if incorrect 
For Kazakhstan dial code is +7. CMIIW
<img width="724" alt="Screenshot 2021-05-14 at 4 20 39 PM" src="https://user-images.githubusercontent.com/6416095/118261076-b18df580-b4d0-11eb-842f-6c23fb165818.png">

**Comment by SURYAKANTSHARMA** [comment]
@freakdragon  can you please update to latest version the bug again. Thanks I will fix asap

**Comment by freakdragon** [comment]
@SURYAKANTSHARMA 
Kazakhstan code is still "77" but it has to be "7"

https://github.com/SURYAKANTSHARMA/CountryPicker/blob/master/CountryPicker/CountryPicker/Constant.swift

at string 117:

`    "KZ": "77",`

**Comment by SURYAKANTSHARMA** [comment]
Ok fixing

**Comment by SURYAKANTSHARMA** [comment]
Fixed @freakdragon 
 🎉  Congrats
 🚀  SKCountryPicker (1.3.1) successfully published
 📅  May 14th, 18:21
 🌎  https://cocoapods.org/pods/SKCountryPicker
 👍  Tell your friends!
