### ISSUE TITLE
localising the country list based on application and not based on device language

### ISSUE THREAD

**Issue by bhargavthakkar2912** [SURYAKANTSHARMA/CountryPicker#79]
Hello 
Can you guide me on how I can view the localised name of the country based on application language. 
Suppose my application is in Arabic and my device is English how can I convert the country list to Arabic. 

Thanking you in Advance

**Comment by bhargavthakkar2912** [comment]
Duplicate of #60

**Comment by SURYAKANTSHARMA** [comment]
Not supported yet cc @Sharkesm 
@bhargavthakkar2912 can you want to try I think we need to add localized files as well

**Comment by SURYAKANTSHARMA** [comment]
closing no need of action right now.
