### ISSUE TITLE
Åland islands, Cayman islands, Jamaica possibly wrong phone codes

### ISSUE THREAD

**Issue by freakdragon** [SURYAKANTSHARMA/CountryPicker#80]
Åland islands ("AX") must be +358
Cayman islands ("KY") must be +1345
Cayman Jamaica ("JM") must be +1876

Check please.

**Comment by SURYAKANTSHARMA** [comment]
@freakdragon  I will appreciate if you can raise pr on fixing all at once

**Comment by freakdragon** [comment]
https://github.com/SURYAKANTSHARMA/CountryPicker/pull/81

**Comment by freakdragon** [comment]
@SURYAKANTSHARMA added pull request

**Comment by SURYAKANTSHARMA** [comment]
Ok thanks 🙏

**Comment by Sharkesm** [comment]
PR #81 has been approved and merged to master already 😄
