### ISSUE TITLE
Instance no longer returned on `present(on:)` in 1.4.1

### ISSUE THREAD

**Issue by dhritzkiv** [SURYAKANTSHARMA/CountryPicker#87]
**Describe the bug**
In 1.3.2 it was possible to retrieve the instance of the view controller after calling `present`:

```swift
let countryController = CountryPickerWithSectionViewController.presentController(on: self) { ... }
```

^ that's from the README

Now, the call returns `()`

If this is no longer supported, 1.4.1 should have been 2.0.0, as that's a breaking change

**Comment by Sharkesm** [comment]
@dhritzkiv Good point that you raised. 

@SURYAKANTSHARMA Could we proceed with updating the README based on the recent changes that you made.

**Comment by SURYAKANTSHARMA** [comment]
@Sharkesm should we close this ?

**Comment by dhritzkiv** [comment]
In 1.3.2 I was doing this:

```swift
let countryController = CountryPickerWithSectionViewController.presentController(on: self) { [weak self] (country: Country) in
    // code
}

countryController.title = "" // custom title

countryController.detailFont = UIFont.systemFont(ofSize: 17)
countryController.detailColor = UIColor.systemGray
countryController.labelFont = UIFont.systemFont(ofSize: 17)
countryController.labelColor = UIColor.systemGray

countryController.flagStyle = .corner
```

I'm unable to apply these in the configuration block

**Comment by Sharkesm** [comment]
@dhritzkiv I think you can still apply the configuration of the controller as instructed on the README file. 

@SURYAKANTSHARMA For that case since there's code-breaking would be best to update the versioning to avoid any confusion then close this issue.

**Comment by dhritzkiv** [comment]
It doesn't look to be the case. More than just that API changed:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1349865/153801974-7b647fb9-0fd1-4ba5-86ad-3c8d9144a2dc.png">

**Comment by SURYAKANTSHARMA** [comment]
use `countryController. configuration.detailFont` will update major version.

**Comment by Sharkesm** [comment]
@dhritzkiv Updated the README file on the styling section. Please confirm as to whether the styling configuration is exposed for the current version or else we may proceed to close this thread. 

cc/ @SURYAKANTSHARMA

**Comment by SURYAKANTSHARMA** [comment]
I have not delete live version as per [this](https://stackoverflow.com/a/31052949 ).  but had updated new version will reflect soon 2.0.0
