### ISSUE TITLE
Mac Catalyst Support

### ISSUE THREAD

**Issue by ohomaidi** [SURYAKANTSHARMA/CountryPicker#88]
I am getting "Missing countries plist file from path: ./ -- file:///Users/xxx/Library/Containers/com.xxx.xxx" when trying to run on  Catalyst. I am assuming its not supported? Could you please confirm?

Many many thanks for the amazing library. It looks great on iOS.

**Comment by Sharkesm** [comment]
@SURYAKANTSHARMA Do we have any support for Mac Catalyst support in place?

**Comment by SURYAKANTSHARMA** [comment]
Not yet. @ohomaidi  You can open PR in case you want. cc @Sharkesm
