### ISSUE TITLE
Using of custom CountryListDataSource doesn't prevent the call of CountryManager.shared `allCountries` method

### ISSUE THREAD

**Issue by freakdragon** [SURYAKANTSHARMA/CountryPicker#89]
While using of method `presentController` of `CountryPickerWithSectionViewController` (`CountryPickerWithSectionViewController.swift` row 45) it calls init method of `CountryPickerController` (`CountryPickerController.swift` row 113) which creates `CountryPickerEngine` (`CountryPickerController.swift` row 115). But when the initiator of `CountryPickerEngine` (CountryPickerEngine.swift row 15) called the `filterOptions` parameter calling the initiator of `CountryManager.shared` because this parameter doesn't sends.

Probably workarounds:
* change the initiator of `CountryPickerEngine` to `init(countries: [Country] = CountryManager.shared.countries, filterOptions: Set<CountryFilterOption> = [.countryName])`
* add default value for parameter `filterOptions` when creating the `CountryPickerEngine` in init method of `CountryPickerController`
* change init method of `CountryPickerController` and method `presentController` of `CountryPickerWithSectionViewController`

**Comment by SURYAKANTSHARMA** [comment]
@freakdragon  can you raise PR for same will check.
