### ISSUE TITLE
A way of setting the last selected country

### ISSUE THREAD

**Issue by joedefa01** [SURYAKANTSHARMA/CountryPicker#90]
I was wondering if there was a way / if you could make a way to set the last selected country. For example i want to show the picker but first i want to set the last selected country to another country before it is presented. I have already selected US for the country and when i show the controller again i want to set the selected country to UK instead because the field i am editing has UK as the selected country

**Comment by SURYAKANTSHARMA** [comment]
@Sharkesm any update on this ?

**Comment by Sharkesm** [comment]
@SURYAKANTSHARMA I haven't had a chance to work on this yet. Hopefully over the weekend I can give it a look and make proper changes for such support.

**Comment by SURYAKANTSHARMA** [comment]
@Sharkesm  Gentle remainder

**Comment by vishalkevin11** [comment]
Hey @SURYAKANTSHARMA @Sharkesm Have raised a PR for the above issue. Please review.

**Comment by SURYAKANTSHARMA** [comment]
Hi @joedefa01 as @vishalkevin11 [pr](https://github.com/SURYAKANTSHARMA/CountryPicker/pull/93) is merged please confirmed issue is fixed for you. Thanks guys for reporting  and fixing as well 👍 (this is beauty of open source projects).
