### ISSUE TITLE
EXC_BREAKPOINT Swift runtime failure: Index out of range

### ISSUE THREAD

**Issue by emanuelhc88** [SURYAKANTSHARMA/CountryPicker#91]
**Describe the bug**

We use the Bugsnag platform to map bugs and a frequent error that happened to our users:

EXC_BREAKPOINT Swift runtime failure: Index out of range

We were unable to replicate it, but we observed that it happens sometime after the user opens the keyboard.

Follow the prints:

**Screenshots**
![Screen Shot 2022-06-24 at 17 21 16](https://user-images.githubusercontent.com/93926942/175661711-2792ed43-cdbc-42c9-b812-1879ec6fa0b2.png)

![Screen Shot 2022-06-24 at 17 21 38](https://user-images.githubusercontent.com/93926942/175661750-cc9e1e8f-454d-4d02-af2d-54e61b5fe2c8.png)

**Smartphone (please complete the following information):**
 - Device: Iphone XR
 - OS: iOS 15.5

**Comment by SURYAKANTSHARMA** [comment]
please reopen if can reproduce steps
