### ISSUE TITLE
Unable to see check / tick mark for selected country

### ISSUE THREAD

**Issue by vishalkevin11** [SURYAKANTSHARMA/CountryPicker#94]
**Describe the bug**
 - Unable to see check / tick mark for selected country
**To Reproduce**
1. Open country selection picker
2. Select country
3. Close picker
4. Re-Open country selection picker
5. Now you see no country is selected

**Expected behavior**

- Selected country should show check/tick mark

**Screenshots**

![Screen_Recording_2022-09-30_at_8_01_18_AM_AdobeExpress](https://user-images.githubusercontent.com/9132837/193186047-b57e362d-e397-4b87-9d04-34bd0cf3bae0.gif)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by InsanelyHarsh** [comment]
I would like to take this task, can you make me go through the workflow?

**Comment by vishalkevin11** [comment]
Hey @InsanelyHarsh,

Thank you for your interest. So the following describes our issue

We have a `tickMark` image added to our bundle. We have the code to show the image when the cell is selected. For some reason (_mainly the image is not in the Bundle anymore_) we don't see the cell chosen showing the `tickMark` image. This is what has to be fixed.

**Comment by SURYAKANTSHARMA** [comment]
@InsanelyHarsh let me know in case you cannot pick this ?
There is some issue in countryPickerSwiftUIExample project it using SPM cc @vishalkevin11

**Comment by SURYAKANTSHARMA** [comment]
@vishalkevin11 you can check now on latest SPM 2.1.0 it will fix the issue. Let me know in case you find any issue. Thanks for reporting. 👍

**Comment by vishalkevin11** [comment]
@SURYAKANTSHARMA Just verified this. It works like charm, I see the check mark now. Thanks for the quick fix ❤️❤️❤️
