### ISSUE TITLE
Searchbar Customization

### ISSUE THREAD

**Issue by wilav-dev** [SURYAKANTSHARMA/CountryPicker#97]
Hello, I have two questions:

- My primary color is dark green so I want to change the searchbar icon and title to white
- I want to translate Search text to spanish "Buscar"

![Screenshot 2022-11-04 at 9 56 59 PM](https://user-images.githubusercontent.com/71793326/200093878-a3d27d30-f8c0-478e-a0d2-59a5a2f99933.png)

**Comment by SURYAKANTSHARMA** [comment]
> My primary color is dark green so I want to change the searchbar icon and title to white
> I want to translate Search text to spanish "Buscar"
> 
For both of them there is no support as such may be you can fork the repo to make changes or feel free to raise pr to us will see if we can merge into master
