### ISSUE TITLE
Add/Remove country 

### ISSUE THREAD

**Issue by imrankst1221** [SURYAKANTSHARMA/CountryPicker#98]
Is there any way to add or remove the country from the list? In my case, I required some selected countries.

**Comment by SURYAKANTSHARMA** [comment]
You can check `PickerViewController` to set custom set of country it has example with pickerview

**Comment by MahdiRB** [comment]
Is there any way to use custom selection of countries in `CountryPickerWithSectionViewController` not in `PickerViewController`?
